### ISSUE TITLE
Preserve Case doesn't work after installing Sublime Text 3 bulid 3103

### ISSUE THREAD

**Issue by ahmadhsalim** [philippotto/Sublime-MultiEditUtils#22] opened 2016-04-06 04:53 UTC
When I select `MultiEditUtils: Preserve Case` from the command palette, all of the selections are gone, therefore the new string I entered is not reflected. This happened after installing the Sublime Text 3 update that was released recently.

**Comment by philippotto** [comment] 2016-04-15 19:09
I'm running 3103 and cannot reproduce this, unfortunately. Which OS are you running?

**Comment by leolower** [comment] 2016-04-20 11:13
@philippotto this stopped working for me a few weeks ago. I am using build 3065 on Ubuntu. 

![gifrecord_2016-04-20_080957](https://cloud.githubusercontent.com/assets/170611/14672660/957199d8-06cf-11e6-96a6-4b0c9aa712ef.gif)

**Comment by philippotto** [comment] 2016-04-21 14:19
I just tested it under Ubuntu and confirm this bug. Unfortunately, I'm not sure how to work around this. The culprit is this line `inputView.run_command("select_all")`, but I assume the underlying problem is a bug in ST under Ubuntu.

Any ideas how we could fix this? A very naive work around would be to remove the select_all statement when run under Ubuntu.

**Comment by philippotto** [comment] 2016-04-21 17:15
Should be fixed thanks to #24.

**Closed by philippotto** 2016-04-21 17:15 UTC
